### ISSUE TITLE
Slime fabricator just makes air

### ISSUE THREAD

**Issue by toruPuchuu** [MysticMods/MysticalMachinery#1]
In OpenDevCraft, the Slime Fabricator consumes RF, but doesn't output anything. When I right click on the Slime Fabricator, it reports that it contains 50 air. 

BTW, noobanidus (OpenDevCraft mod author) mistakenly opened a Mystical Powers issue for the broken Slime Fabricator a few weeks ago.

**Comment by noobanidus** [comment]
I'm not entirely sure why it's still showing up as "Mystical Machinery", I need to look into it further, but I've split Mystical Machinery's RF-related items out into Mystical Powers. The latest update of Mystical Powers should hopefully fix this problem.

**Comment by noobanidus** [comment]
Although it may need you to break and re-place it.

**Comment by noobanidus** [comment]
(Also OpenDevCraft will be updated soon.)
